"""Add failure_reason to documents

Revision ID: 076cfe04b66f
Revises: 586a40967923
Create Date: 2026-07-20 15:29:28.065607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076cfe04b66f'
down_revision: Union[str, None] = '586a40967923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('venue', sa.String(length=255), nullable=True))
    op.add_column('calendar_events', sa.Column('trainer_remarks', sa.Text(), nullable=True))
    op.add_column('calendar_events', sa.Column('material_ref', sa.String(length=255), nullable=True))
    op.add_column('calendar_events', sa.Column('attendance_threshold_breached', sa.Boolean(), nullable=False))
    op.add_column('calendar_events', sa.Column('reschedule_triggered', sa.Boolean(), nullable=False))
    op.alter_column('calendar_events', 'calendar_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'dept_yearly'::character varying"))
    op.alter_column('calendar_events', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('calendar_events', 'is_carried_forward',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('documents', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.alter_column('documents', 'sequence_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'sequence_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_column('documents', 'failure_reason')
    op.alter_column('calendar_events', 'is_carried_forward',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('calendar_events', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('calendar_events', 'calendar_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'dept_yearly'::character varying"))
    op.drop_column('calendar_events', 'reschedule_triggered')
    op.drop_column('calendar_events', 'attendance_threshold_breached')
    op.drop_column('calendar_events', 'material_ref')
    op.drop_column('calendar_events', 'trainer_remarks')
    op.drop_column('calendar_events', 'venue')
    # ### end Alembic commands ###
