"""phase1_7_complete_schema

Revision ID: 6e986bd02602
Revises: 20550f3a2413
Create Date: 2026-07-15 05:12:42.066102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e986bd02602'
down_revision: Union[str, None] = '20550f3a2413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_assignments', sa.Column('trainer_id', sa.Integer(), nullable=True))
    op.add_column('training_assignments', sa.Column('verified_by_trainer', sa.Boolean(), nullable=False))
    op.add_column('training_assignments', sa.Column('certificate_url', sa.String(length=500), nullable=True))
    op.alter_column('training_assignments', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'training_assignments', 'users', ['trainer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_assignments', type_='foreignkey')
    op.alter_column('training_assignments', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('training_assignments', 'certificate_url')
    op.drop_column('training_assignments', 'verified_by_trainer')
    op.drop_column('training_assignments', 'trainer_id')
    # ### end Alembic commands ###
