"""add_calendar_engine_columns

Revision ID: a406522b4e41
Revises: 6e986bd02602
Create Date: 2026-07-16 14:22:55.943656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a406522b4e41'
down_revision: Union[str, None] = '6e986bd02602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('calendar_events', sa.Column('calendar_type', sa.String(length=50), nullable=True, server_default='dept_yearly'))
    op.add_column('calendar_events', sa.Column('status', sa.String(length=50), nullable=True, server_default='draft'))
    op.add_column('calendar_events', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('calendar_events', sa.Column('is_carried_forward', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('calendar_events', sa.Column('carry_forward_reason', sa.Text(), nullable=True))
    op.add_column('calendar_events', sa.Column('actual_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'calendar_events', 'users', ['approved_by'], ['id'])
    op.add_column('documents', sa.Column('sequence_order', sa.Integer(), nullable=True, server_default='1'))
    op.add_column('users', sa.Column('employee_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'employee_type')
    op.drop_column('documents', 'sequence_order')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'actual_date')
    op.drop_column('calendar_events', 'carry_forward_reason')
    op.drop_column('calendar_events', 'is_carried_forward')
    op.drop_column('calendar_events', 'approved_by')
    op.drop_column('calendar_events', 'status')
    op.drop_column('calendar_events', 'calendar_type')
    op.drop_column('calendar_events', 'department')
    # ### end Alembic commands ###
